### ISSUE TITLE
TypeError: a new-style class can't have only classic bases

### ISSUE THREAD

**Issue by mehul009** [numpy/numpy-refactor#6]
windows 10, ironpython 2.7.9

Running from numpy source directory.Traceback (most recent call last):
  File "setup.py", line 200, in <module>
  File "setup.py", line 176, in setup_package
  File "C:\Program Files\IronPython 2.7\numpy-refactor-refactor\numpy-refactor-refactor\numpy\distutils\core.py", line 25, in <module>
  File "C:\Program Files\IronPython 2.7\numpy-refactor-refactor\numpy-refactor-refactor\numpy\distutils\command\scons.py", line 11, in <module>
  File "C:\Program Files\IronPython 2.7\numpy-refactor-refactor\numpy-refactor-refactor\numpy\distutils\fcompiler\__init__.py", line 62, in <module>
TypeError: a new-style class can't have only classic bases

**Comment by PaulieRocks** [comment]
Hi there , 

Were there any resolutions to this ??

Thanks
